[package]
name = "maze_solver"
version = "0.1.0"
authors = ["k-wozniak <kamil.krzysztof.wozniak@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.8"
lapp = "0.4.0"